// Categories Data for Homepage
export const categoriesData = [
  {
    id: 1,
    name: "Pre School",
    description: "Quality uniforms for pre-school children",
    image: "/img/images/Categories/pre-school-cat.jpg",
    link: "/pre-school",
    productCount: 12,
  },
  {
    id: 2,
    name: "Primary School",
    description: "Complete primary school uniform range",
    image: "/img/images/Categories/primary-school-cat.jpg",
    link: "/primary-school",
    productCount: 15,
  },
  {
    id: 3,
    name: "High School",
    description: "Professional high school attire",
    image: "/img/images/Categories/high-school-cat.jpg",
    link: "/high-school",
    productCount: 18,
  },
  {
    id: 4,
    name: "Workwear",
    description: "Durable workwear for all industries",
    image: "/img/images/Categories/workwear-cat.jpg",
    link: "/workwear",
    productCount: 20,
  },
  {
    id: 5,
    name: "Officewear",
    description: "Professional office clothing",
    image: "/img/images/Categories/officewear-cat.jpg",
    link: "/officewear",
    productCount: 16,
  },
  {
    id: 6,
    name: "Medical Scrubs",
    description: "Comfortable medical scrubs and lab coats",
    image: "/img/images/Categories/medical-cat.jpg",
    link: "/medical-scrubs",
    productCount: 15,
  },
  {
    id: 7,
    name: "Chef & Kitchen",
    description: "Chef uniforms and kitchen wear",
    image: "/img/images/Categories/chef-cat.jpg",
    link: "/chef-kitchen-uniforms",
    productCount: 12,
  },
  {
    id: 8,
    name: "Industrial & Mining",
    description: "Heavy-duty industrial uniforms",
    image: "/img/images/Categories/industrial-cat.jpg",
    link: "/industrial-mining",
    productCount: 18,
  },
];
